
name: web_app_auto_tests

on: 
  push:
    branches: [ master, develop ]

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repository
        uses: actions/checkout@v1

######################################################
      # Runs a single command using the runners shell
      - name: check that everything is installed
        run: ls -la
        
      # Runs making an Artifact
      #- name: make tar archive
        #run: |
        #  tar cvf artifact.tar *
        #  bzip2 artifact.tar
        #  echo "${{ secrets.RSA_KEY_FOR_ANSIBLE_SERVER }}" > key.pem
        #  chmod 600 key.pem



        





