
name: web_app_auto_tests

on: 
  push:
    branches: [ master, develop ]

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repository
        uses: actions/checkout@v1

######################################################
      # Runs a single command using the runners shell
      - name: check that everything is installed
        run: ls -la
        
      # my Testing the environment
      - name: Testing the environment
        run: |
          git branch
          pwd
          sudo apt update
          sudo apt install nodejs -y
          nodejs --version




        





